audit_header: false
title: "North Central CT and Western MA's Best Real Estate Training - Lori Gabriel"
description: Lori Gabriel, a top Real Estate Agent in North Central CT and Western MA, shares her own internal real estate agent training for free. Her Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: http://teamgabriel.eventbrite.com/
  - title: Free Strategy Call
    url: /strategy-call/
client:
  name: Lori Gabriel
  title:
  license_number:
  about_markdown: |
    A real estate veteran and experienced agent, I have been in real estate since 1993 and has worked hard over the past 25 years to build my brand and my own business. Born and raised in the Agawam, MA area, my extensive knowledge and expertise of the real estate market in Connecticut and Massachusetts have become second nature over the course of my lifetime and work in the industry. As a certified real estate Broker, I have received dozens of specialty achievement awards and certifications including, ABR (Accredited Buyer Representative) and CRS (Certified Residential Specialist), for my dedication to real estate for nearly three decades. As a member of the Cartus Relocation Company, I have the opportunity to assist in relocating USAA Military Families with Navy Federal Credit Union. I also work closely with a Builders and Developers to build new construction homes.
  market: North Central CT and Western MA
  brand: Team Gabriel
  brokerage: Coldwell Banker
  address: 74 Miller Road Broad Brook, CT 06016
  phone: 860-623-0883
  phone_type:
  phone2:
  phone2_type:
  email: ghs@teamgabriel.net
  url: http://teamgabriel.net

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how Team Gabriel can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/TeamGabriel.RealEstate/
  linkedin_url: https://www.linkedin.com/in/lorigabriel/
  gplus_url:
  youtube_url:
  twitter_url: https://twitter.com/_team_gabriel
  instagram_url: https://www.instagram.com/team_gabriel_lori_gabriel/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'North Central CT and Western MA Real Estate Podcast with Lori Gabriel'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the North Central CT and Western MA Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Team Gabriel - your professional North Central CT and Western MA Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in North Central CT and Western MA, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Lori Gabriel'

images:
  client_headshot_path: /img/headshot.png
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: North Central CT and Western MA Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#3286aa'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
